# fly.toml app configuration file generated for doxxcaster on 2023-12-12T18:22:14+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "doxxcaster"
primary_region = "sjc"

[processes]
worker = "python doxxcaster/bot/main.py"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
